version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: neuroclear-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neuroclear
    ports:
      - "5434:5432"
    volumes:
      - neuroclear_data:/var/lib/postgresql/data

volumes:
  neuroclear_data:
