version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: assessmind-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assessmind
    ports:
      - "5434:5432"
    volumes:
      - assessmind_data:/var/lib/postgresql/data

volumes:
  assessmind_data:
